openapi: 3.0.3
info:
  title: SkyTale API Documentation
  version: 1.0.0

servers:
  - url: "{server}"
    variables:
      server:
        default: "http://localhost:8080"

tags:
  - name: encode
    description: encode operations
  - name: decode
    description: decode operations
  - name: admin
    description: administrative operations


paths:
  /v1/encode:
    post:
      summary: Enqueues message to be encrypted.
      operationId: encodeMessage
      tags:
        - encode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncodeMessageRequest'
      responses:
        201:
          description: Message queued for encryption.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncodeMessageResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/decode:
    post:
      summary: Enqueues a request to decrypt an encoded message.
      operationId: decodeMessage
      tags:
        - decode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DecodeMessageRequest'
      responses:
        201:
          description: Message queued for decryption.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecodeMessageResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:

    DecodeMessageRequest:
      title: DecodeMessageRequest
      required:
        - encode-guid
      properties:
        encode-guid:
          type: string
          description: GUID of encoded message to decrypt
          example: f1a59a5d-8b29-4cde-ba10-dc025c7c5042
        secret:
          type: string
          description: client secret added to encryption context. must match the secret provided to the encode request.
          example: RQ!9*0XCDV5r*a98

    DecodeMessageResponse:
      title: DecodeMessageResponse
      required:
        - decode-guid
      properties:
        decode-guid:
          type: string
          description: GUID of decrypted message
          example: 2c9d2718-e573-4de0-bad9-60e4384c4928

    EncodeMessageRequest:
      title: EncodeMessageRequest
      required:
        - message
        - secret
      properties:
        message:
          type: string
          description: plaintext message to encrypt
          example: The chicken has flown the coop. I repeat. The chicken has flown the coop.
        secret:
          type: string
          description: client secret added to encryption context. the same secret must be provided on decode operations.
          example: RQ!9*0XCDV5r*a98

    EncodeMessageResponse:
      title: EncodeMessageResponse
      required:
        - encode-guid
      properties:
        encode-guid:
          type: string
          description: GUID of encoded message
          example: f1a59a5d-8b29-4cde-ba10-dc025c7c5042

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
