openapi: 3.0.3
info:
  title: SkyTale API Documentation
  version: 1.0.0

servers:
  - url: "{server}"
    variables:
      server:
        default: "http://localhost:8080"

tags:
  - name: encode
    description: encode operations
  - name: decode
    description: decode operations
  - name: admin
    description: administrative operations


paths:
  /admin/secrets/{uuid}:
    get:
      summary: Returns the encoded message ciphertext from the secrets bucket.
      operationId: getSecret
      tags:
        - admin
      parameters:
        - in: path
          name: "uuid"
          required: true
          description: "UUID of encrypted message."
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        200:
          description: Message Ciphertext
          content:
            text/plain:
              schema:
                type: string
                example: TBD...
          headers:
            X-S3-Bucket-Name:
              description: Name of the S3 bucket storing message.
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    head:
      summary: Confirms the existence of an encoded secret in the secrets bucket.
      operationId: secretExists
      tags:
        - admin
      parameters:
        - in: path
          name: "uuid"
          required: true
          description: "UUID of encrypted message."
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        204:
          description: Message Details.
          headers:
            Content-Length:
              description: Message Lengths
              schema:
                type: integer
            X-S3-Bucket-Name:
              description: Name of the S3 bucket storing message.
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /admin/plaintext/{uuid}:
    get:
      summary: Returns the message plaintext from the decode bucket.
      operationId: getDecodedSecret
      tags:
        - admin
      parameters:
        - in: path
          name: "uuid"
          required: true
          description: "UUID of decode message."
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        200:
          description: Message Plaintext
          content:
            text/plain:
              schema:
                type: string
                example: the chicken has flown the coopy
          headers:
            X-S3-Bucket-Name:
              description: Name of the S3 bucket storing message.
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    head:
      summary: Confirms the existence of an decoded secret in the decode bucket.
      operationId: decodedSecretExists
      tags:
        - admin
      parameters:
        - in: path
          name: "uuid"
          required: true
          description: "UUID of decoded message."
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        204:
          description: Message Details.
          headers:
            Content-Length:
              description: Message Lengths
              schema:
                type: integer
            X-S3-Bucket-Name:
              description: Name of the S3 bucket storing message.
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /v1/encode:
    post:
      summary: Enqueues message to be encrypted.
      operationId: encodeMessage
      tags:
        - encode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncodeMessageRequest'
      responses:
        201:
          description: Message queued for encryption.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncodeMessageResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/decode:
    post:
      summary: Enqueues a request to decrypt an encoded message.
      operationId: decodeMessage
      tags:
        - decode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DecodeMessageRequest'
      responses:
        201:
          description: Message queued for decryption.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecodeMessageResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:

    DecodeMessageRequest:
      description: Decode Message POST Request
      type: object
      properties:
        uuid:
          description: uuid of encoded message to decrypt
          example: f1a59a5d-8b29-4cde-ba10-dc025c7c5042
          $ref: "#/components/schemas/UUID"

        secret:
          type: string
          description: client secret added to encryption context. must match the secret provided to the encode request.
          example: RQ!9*0XCDV5r*a98
      required:
        - uuid
        - secret

    UUID:
      type: string
      format: uuid

    DecodeMessageResponse:
      description: Decode Message Response
      properties:
        uuid:
          description: uuid of decrypted message
          example: 2c9d2718-e573-4de0-bad9-60e4384c4928
          $ref: "#/components/schemas/UUID"

    EncodeMessageRequest:
      description: Encode Message POST Request
      properties:
        message:
          type: string
          description: plaintext message to encrypt
          example: The chicken has flown the coop. I repeat. The chicken has flown the coop.
        secret:
          type: string
          description: client secret added to encryption context. the same secret must be provided on decode operations.
          example: RQ!9*0XCDV5r*a98
      required:
        - message
        - secret

    EncodeMessageResponse:
      description: Encode Message Response
      properties:
        uuid:
          description: uuid of encoded message
          example: f1a59a5d-8b29-4cde-ba10-dc025c7c5042
          $ref: "#/components/schemas/UUID"

    Error:
      description: "Error"
      type: object
      properties:
        code:
          description: "HTTP Status Code"
          type: integer
          format: int32
        message:
          description: "HTTP Status Message"
          type: string
        description:
          description: "Error description"
          type: string
        invalidParameters:
          $ref: "#/components/schemas/InvalidParameterArray"

    InvalidParameter:
      description: "Invalid Parameter"
      type: object
      properties:
        name:
          description: "Parameter name"
          type: string
        description:
          description: "Parameter description"
          type: string

    InvalidParameterArray:
      description: "Invalid parameter list"
      type: array
      items:
        $ref: "#/components/schemas/InvalidParameter"