---
spring:
  application:
    name: ${project.name}
  profiles:
    active:
      - local

iceburg:
  foo: bar
  #traceEnabled: false

skytale:
  encodeQueue: ${project.name}-encode
  decodeQueue: ${project.name}-decode
