---
camel:
  springboot:
    main-run-controller: true

spring:
  application:
    name: ${project.name}
  main:
    web-application-type: NONE
  profiles:
    active:
      - local

iceburg:
  foo: bar
  #traceEnabled: false

skytale:
  encodeQueue: skytale-encode
  decodeQueue: skytale-decode
